ALTER TABLE `GHEALTH_AGENCY_PRODUCT` ADD COLUMN `START_TIME`  datetime  COMMENT '优惠开始时间' AFTER `AGENCY_PRICE`;
ALTER TABLE `GHEALTH_AGENCY_PRODUCT` ADD COLUMN `END_TIME`   datetime    COMMENT '优惠结束时间'     AFTER `START_TIME`;
ALTER TABLE `GHEALTH_AGENCY_PRODUCT` ADD COLUMN `DISCOUNT_PRICE`       decimal(10,2)          COMMENT '优惠价格'    AFTER `END_TIME`;
ALTER TABLE `GHEALTH_AGENCY_PRODUCT` ADD COLUMN `DISCOUNT`     tinyint(1)     NOT NULL     COMMENT '优惠标记 0-未优惠 1-已优惠'      AFTER `DISCOUNT_PRICE`;
